In [56]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [57]:
df=pd.read_csv('data/allergy.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2475 entries, 0 to 2474
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   allergyid             2475 non-null   int64
 1   patientunitstayid     2475 non-null   int64
 2   allergyoffset         2475 non-null   int64
 3   allergyenteredoffset  2475 non-null   int64
 4   allergynotetype       2475 non-null   object
 5   specialtytype         2475 non-null   object
 6   usertype              2475 non-null   object
 7   rxincluded            2475 non-null   bool
 8   writtenineicu         2475 non-null   bool
 9   drugname              1480 non-null   object
 10  allergytype           2475 non-null   object
 11  allergyname           2472 non-null   object
 12  drughiclseqno         1480 non-null   float64
dtypes: bool(2), float64(1), int64(4), object(6)
memory usage: 217.7+ KB

,allergyid,patientunitstayid,allergyoffset,allergyenteredoffset,allergynotetype,specialtytype,usertype,rxincluded,writtenineicu,drugname,allergytype,allergyname,drughiclseqno
0,357144,243097,2549,2552,Comprehensive Progress,eCM Primary,THC Nurse,True,True,NaN,Non Drug,penicillins,NaN
1,442253,243097,1288,1294,Comprehensive Progress,eCM Primary,THC Nurse,True,True,CODEINE PHOSPHATE,Drug,CODEINE PHOSPHATE,1721.0
2,357143,243097,2549,2552,Comprehensive Progress,eCM Primary,THC Nurse,True,True,CODEINE PHOSPHATE,Drug,CODEINE PHOSPHATE,1721.0
3,329929,243097,21,28,Admission,eCM Primary,THC Nurse,True,True,NaN,Non Drug,penicillins,NaN
4,363374,243097,3988,3989,Comprehensive Progress,eCM Primary,THC Nurse,True,True,CODEINE PHOSPHATE,Drug,CODEINE PHOSPHATE,1721.0

In [58]:
# supprimer les colonnes inutiles
df=df.drop(['allergyid','patientunitstayid','drughiclseqno','drugname'],axis=1)
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2475 entries, 0 to 2474
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   allergyoffset         2475 non-null   int64
 1   allergyenteredoffset  2475 non-null   int64
 2   allergynotetype       2475 non-null   object
 3   specialtytype         2475 non-null   object
 4   usertype              2475 non-null   object
 5   rxincluded            2475 non-null   bool
 6   writtenineicu         2475 non-null   bool
 7   allergytype           2475 non-null   object
 8   allergyname           2472 non-null   object
dtypes: bool(2), int64(2), object(5)
memory usage: 140.3+ KB

,allergyoffset,allergyenteredoffset,allergynotetype,specialtytype,usertype,rxincluded,writtenineicu,allergytype,allergyname
0,2549,2552,Comprehensive Progress,eCM Primary,THC Nurse,True,True,Non Drug,penicillins
1,1288,1294,Comprehensive Progress,eCM Primary,THC Nurse,True,True,Drug,CODEINE PHOSPHATE
2,2549,2552,Comprehensive Progress,eCM Primary,THC Nurse,True,True,Drug,CODEINE PHOSPHATE
3,21,28,Admission,eCM Primary,THC Nurse,True,True,Non Drug,penicillins
4,3988,3989,Comprehensive Progress,eCM Primary,THC Nurse,True,True,Drug,CODEINE PHOSPHATE

In [60]:
# supprimer les lignes avec des valeurs manquantes
df=df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2472 entries, 0 to 2474
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   allergyoffset         2472 non-null   int64
 1   allergyenteredoffset  2472 non-null   int64
 2   allergynotetype       2472 non-null   object
 3   specialtytype         2472 non-null   object
 4   usertype              2472 non-null   object
 5   rxincluded            2472 non-null   bool
 6   writtenineicu         2472 non-null   bool
 7   allergytype           2472 non-null   object
 8   allergyname           2472 non-null   object
dtypes: bool(2), int64(2), object(5)
memory usage: 159.3+ KB

In [61]:
dummies=[]
cols =["rxincluded","writtenineicu","specialtytype"]
for col in cols:
    dummies.append(pd.get_dummies(df[col], prefix=col))
dummies_df=pd.concat(dummies,axis=1)
df=pd.concat((df,dummies_df),axis=1)
df=df.drop(cols,axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2472 entries, 0 to 2474
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   allergyoffset                               2472 non-null   int64
 1   allergyenteredoffset                        2472 non-null   int64
 2   allergynotetype                             2472 non-null   object
 3   usertype                                    2472 non-null   object
 4   allergytype                                 2472 non-null   object
 5   allergyname                                 2472 non-null   object
 6   rxincluded_False                            2472 non-null   bool
 7   rxincluded_True                             2472 non-null   bool
 8   writtenineicu_False                         2472 non-null   bool
 9   writtenineicu_True                          2472 non-null   bool
 10  specialtytype_critical care medicine (CCM)  2472 non-null   bool
 11  specialtytype_eCM Primary                   2472 non-null   bool
dtypes: bool(6), int64(2), object(4)
memory usage: 149.7+ KB

In [62]:
# diviser les données en ensembles d'entraînement et de test
X=df.drop('allergytype',axis=1)
y=df['allergytype']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)